# name: "AlternativeBA"
# name: "CA-DCA_UCA"
# name: "CDCA-LCA_UDCA"
# name: "MurineCDCA-MCA_MDCA"
name: 

pathway_title: "{name}"
organism: "Homo sapiens" # "Mus musculus"

input:
  folder: "C:/Users/deyan/Desktop/BIOINFORMATICA/1TFM/src/examples/data/"
  id_data_file: "{name}.tsv"
  relations_file: "{name}_relationships.tsv"
  delimiter: "\t"

output:
  folder: "C:/Users/deyan/Desktop/BIOINFORMATICA/1TFM/src/examples/data/"
  filename: "{name}.gpml"

logging:
  level: "INFO"
  format: "%(levelname)s: %(message)s"