input_folder: c:/Users/dborrotoa/Desktop/TFM/pathways_raw
output_folder: c:/Users/dborrotoa/Desktop/TFM/pathways_updated
loglevel: INFO
verbose: false

# FOLDERS
# home
    # INPUT_FOLDER = "C:/Users/deyan/Desktop/BIOINFORMATICA/1TFM/pathways_raw"
    # OUTPUT_FOLDER = "C:/Users/deyan/Desktop/BIOINFORMATICA/1TFM/pathways_updated"
# lab
    # INPUT_FOLDER = "c:/Users/dborrotoa/Desktop/TFM/pathways_raw/"
    # OUTPUT_FOLDER = "c:/Users/dborrotoa/Desktop/TFM/pathways_updated/"